const orderActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FECTH_ORDERS_SUCCESS: "FECTH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  SET_ORDER_STATUS_COMPLETE: "SET_ORDER_STATUS_COMPLETE",
  SET_ORDER_STATUS_CLOSED: "SET_ORDER_STATUS_CLOSED",
  SET_ORDER_STATUS_FAILURE: "SET_ORDER_STATUS_FAILURE"
}

export default orderActionTypes;