const orderActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FECTH_ORDERS_SUCCESS: "FECTH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE"
}

export default orderActionTypes;